### ISSUE TITLE
dikicli outdated dependences

### ISSUE THREAD

**Issue by karolszk** [silenc3r/dikicli#8]
Hi!

I am using dikicli with great success but it has outdated python packages dependences actually, like listed below:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

dikicli 0.4.3 requires beautifulsoup4==4.9.3, but you have beautifulsoup4 4.11.1 which is incompatible.
dikicli 0.4.3 requires certifi==2020.6.20, but you have certifi 2021.10.8 which is incompatible.
dikicli 0.4.3 requires chardet==3.0.4, but you have chardet 4.0.0 which is incompatible.
dikicli 0.4.3 requires idna==2.10, but you have idna 3.3 which is incompatible.
dikicli 0.4.3 requires requests==2.24.0, but you have requests 2.27.1 which is incompatible.
dikicli 0.4.3 requires soupsieve==2.0.1; python_version >= "3.0", but you have soupsieve 2.3.2.post1 which is incompatible.
dikicli 0.4.3 requires urllib3==1.25.11, but you have urllib3 1.26.9 which is incompatible.

**Comment by silenc3r** [comment]
I've removed version specifiers from requirements.txt and it should work now.

**Comment by karolszk** [comment]
Thank you! Now dependencies are OK.
